package EngineUtil;

import java.util.Random;

//"Fancy" magic bitboards for sliding piece attacks. For each square, the relevant blockers
//(occupied & mask) are hashed with a multiply-and-shift into an index into a precomputed attack table.
//"Fancy" means every square gets its own variable-sized slice of one shared table (sized 2^bitsInMask),
//instead of a fixed worst-case 4096/512 entries per square.
//Square indexing matches the rest of the engine: index = row * 8 + col, row 0 being the top of the board.
public final class MagicBitboards {

    //generated by main() below; magics depend on the square indexing, so regenerate them if that ever changes
    private static final long[] ROOK_MAGICS = {
        0x0080008420144000L, 0x0140001000402000L, 0x8100200100081040L, 0x0580100181040800L,
        0x0480040002480180L, 0x020002001004C108L, 0x06002600180104ACL, 0x0A00010200804024L,
        0x1102800320814002L, 0xC000808040002000L, 0x0202802000821000L, 0x4210800800801000L,
        0x8008808044004800L, 0x0006002418100200L, 0x0A00800200010080L, 0x0202000208804114L,
        0x2010208000400080L, 0x1080484004201000L, 0x1062060020408410L, 0x4810010009001024L,
        0x4400808008000401L, 0x9421010002080400L, 0x4208840002100801L, 0x8500020000804104L,
        0x20A0400080208000L, 0x8840008080402008L, 0x0450200080100080L, 0x00100400C02800C0L,
        0x0A48000880040080L, 0x1100020080800400L, 0x000A921400900148L, 0x0033004600008904L,
        0x4202804002800020L, 0x3118804202002504L, 0x0004208842001200L, 0x0014C80084801000L,
        0x0000080080800400L, 0x0922800400800200L, 0x8442000142008418L, 0x0020800040800100L,
        0x1400400080008020L, 0x0010002008484002L, 0x0400200010008080L, 0x4028001000088080L,
        0x4408000400808008L, 0x0129000400090052L, 0x8001001200110004L, 0x4000804084020001L,
        0x1080002080400080L, 0x6A0B950022004200L, 0x8004401200268200L, 0x0002000820411600L,
        0x0481480080040280L, 0xC001000802040100L, 0x00D1000C06000300L, 0x0026010084004200L,
        0x2001C81100208001L, 0x0040002080110041L, 0x00410011A000400DL, 0x2081002208041001L,
        0x0002000804201002L, 0x5101000A28040029L, 0x0100080112489004L, 0x02000E4400288102L
    };

    private static final long[] BISHOP_MAGICS = {
        0x9120024202040010L, 0x2848084884044042L, 0x211000C20041A022L, 0x4002208A01403034L,
        0x0004042004112000L, 0x6002021004120500L, 0x0022080202101041L, 0x0102020382849000L,
        0x0000082089840500L, 0x400204C104010200L, 0x0022460202060900L, 0x0400110502000010L,
        0x10A9840420020000L, 0x0024120150080184L, 0x0008640288443200L, 0x822000908C901000L,
        0x0488100408084810L, 0x0010402022008910L, 0x0084000808002208L, 0x0006800802024012L,
        0x0246008420210880L, 0x0083050200808408L, 0x2004000231040200L, 0x0A04820504088684L,
        0x0002A80120089050L, 0x1410020008320C20L, 0x8000300008008020L, 0x0344010084200880L,
        0x6003010001104000L, 0x0008164002004214L, 0x021811000A014100L, 0x0242020020884140L,
        0x0001104005088800L, 0x0002105069040100L, 0x0200805001010402L, 0x4001020081880080L,
        0x06402080202A0020L, 0x0201100080010060L, 0x03282A04002080C0L, 0x02040040802206A0L,
        0x2008822840482090L, 0x40008C0920080805L, 0x1002002024200800L, 0x080D204202200800L,
        0x0061510212002404L, 0x2448101002108020L, 0x44A1080091100080L, 0x0809014312000900L,
        0x0200611C10402004L, 0x040E010082104006L, 0x0000209400880002L, 0x1002000442022020L,
        0x1200000420820040L, 0x1000091021420204L, 0x0021200202004020L, 0x0220028401002200L,
        0x100603C201904820L, 0x020000420201208BL, 0x0102000422055002L, 0x60C6A04202104400L,
        0x0224000010020880L, 0x0001122044410204L, 0x408C902002042848L, 0x2404010448020040L
    };

    private static final long[] rookMasks = new long[64];
    private static final long[] bishopMasks = new long[64];
    private static final int[] rookShifts = new int[64];
    private static final int[] bishopShifts = new int[64];
    private static final int[] rookOffsets = new int[64];
    private static final int[] bishopOffsets = new int[64];
    private static final long[] rookTable;
    private static final long[] bishopTable;

    private static final int[][] ROOK_DIRECTIONS = {{-1, 0}, {1, 0}, {0, -1}, {0, 1}};
    private static final int[][] BISHOP_DIRECTIONS = {{-1, -1}, {-1, 1}, {1, -1}, {1, 1}};

    static {
        rookTable = new long[initMasks(rookMasks, rookShifts, rookOffsets, ROOK_DIRECTIONS)];
        bishopTable = new long[initMasks(bishopMasks, bishopShifts, bishopOffsets, BISHOP_DIRECTIONS)];
        fillTable(rookTable, rookMasks, ROOK_MAGICS, rookShifts, rookOffsets, ROOK_DIRECTIONS);
        fillTable(bishopTable, bishopMasks, BISHOP_MAGICS, bishopShifts, bishopOffsets, BISHOP_DIRECTIONS);
    }

    private MagicBitboards() {}

    public static long rookAttacks(int square, long occupied) {
        long blockers = occupied & rookMasks[square];
        return rookTable[rookOffsets[square] + (int) ((blockers * ROOK_MAGICS[square]) >>> rookShifts[square])];
    }

    public static long bishopAttacks(int square, long occupied) {
        long blockers = occupied & bishopMasks[square];
        return bishopTable[bishopOffsets[square] + (int) ((blockers * BISHOP_MAGICS[square]) >>> bishopShifts[square])];
    }

    public static long queenAttacks(int square, long occupied) {
        return rookAttacks(square, occupied) | bishopAttacks(square, occupied);
    }

    //fills masks/shifts/offsets and returns the total table size needed for this piece type
    private static int initMasks(long[] masks, int[] shifts, int[] offsets, int[][] directions) {
        int offset = 0;
        for (int square = 0; square < 64; square++) {
            masks[square] = relevantBlockerMask(square, directions);
            int bits = Long.bitCount(masks[square]);
            shifts[square] = 64 - bits;
            offsets[square] = offset;
            offset += 1 << bits;
        }
        return offset;
    }

    private static void fillTable(long[] table, long[] masks, long[] magics, int[] shifts, int[] offsets, int[][] directions) {
        for (int square = 0; square < 64; square++) {
            long mask = masks[square];
            //Carry-Rippler: steps through every subset of `mask`, ending when it wraps back to 0
            long subset = 0L;
            do {
                int index = (int) ((subset * magics[square]) >>> shifts[square]);
                table[offsets[square] + index] = slowAttacks(square, subset, directions);
                subset = (subset - mask) & mask;
            } while (subset != 0);
        }
    }

    //squares whose occupancy can change the attack set: every ray square except the last one before the edge,
    //since a piece on the edge square can't block anything beyond it
    private static long relevantBlockerMask(int square, int[][] directions) {
        long mask = 0L;
        for (int[] dir : directions) {
            int row = square / 8 + dir[0];
            int col = square % 8 + dir[1];
            while (onBoard(row + dir[0], col + dir[1])) {
                mask |= Position.bit(row * 8 + col);
                row += dir[0];
                col += dir[1];
            }
        }
        return mask;
    }

    //reference attack generation by walking rays; only used to build the tables
    private static long slowAttacks(int square, long occupied, int[][] directions) {
        long attacks = 0L;
        for (int[] dir : directions) {
            int row = square / 8 + dir[0];
            int col = square % 8 + dir[1];
            while (onBoard(row, col)) {
                long target = Position.bit(row * 8 + col);
                attacks |= target;
                if ((occupied & target) != 0) break;
                row += dir[0];
                col += dir[1];
            }
        }
        return attacks;
    }

    private static boolean onBoard(int row, int col) {
        return row >= 0 && row < 8 && col >= 0 && col < 8;
    }

    //brute-force search for a magic: try sparse random numbers until one maps every blocker subset
    //to an index without a destructive collision (two subsets sharing an index is fine if their attacks match)
    private static long findMagic(int square, int[][] directions, Random random) {
        long mask = relevantBlockerMask(square, directions);
        int bits = Long.bitCount(mask);
        int size = 1 << bits;
        long[] subsets = new long[size];
        long[] attacks = new long[size];

        long subset = 0L;
        for (int i = 0; i < size; i++) {
            subsets[i] = subset;
            attacks[i] = slowAttacks(square, subset, directions);
            subset = (subset - mask) & mask;
        }

        long[] used = new long[size];
        int[] usedEpoch = new int[size];
        for (int attempt = 1; ; attempt++) {
            //ANDing three randoms gives a number with few set bits, which tends to make better magics
            long magic = random.nextLong() & random.nextLong() & random.nextLong();
            //quick reject: the top byte of mask*magic needs enough bits set to spread indices around
            if (Long.bitCount((mask * magic) & 0xFF00000000000000L) < 6) continue;

            boolean failed = false;
            for (int i = 0; i < size && !failed; i++) {
                int index = (int) ((subsets[i] * magic) >>> (64 - bits));
                if (usedEpoch[index] != attempt) {
                    usedEpoch[index] = attempt;
                    used[index] = attacks[i];
                } else if (used[index] != attacks[i]) {
                    failed = true;
                }
            }
            if (!failed) return magic;
        }
    }

    //run this to regenerate ROOK_MAGICS and BISHOP_MAGICS
    public static void main(String[] args) {
        Random random = new Random(0x5EEDL);
        for (int[][] directions : new int[][][] {ROOK_DIRECTIONS, BISHOP_DIRECTIONS}) {
            System.out.println(directions == ROOK_DIRECTIONS ? "ROOK_MAGICS" : "BISHOP_MAGICS");
            for (int square = 0; square < 64; square++) {
                System.out.printf("0x%016XL,%s", findMagic(square, directions, random), square % 4 == 3 ? "\n" : " ");
            }
        }
    }
}
